--------------------------------------------------------------------------------
-- V18__seed_firm5_john_link_whitelabel.sql
--
-- Cross-host silent-SSO demo fixture for firm 5 (CreativeOne / c1wealth).
--
-- Seeds advisor login user 'john' in firm 5 and wires the two facts the
-- "open the firm-5 whitelabel host in another tab" scenario needs:
--
--   1. john is the SAME PERSON as firm-1 'tim1' — LINKED_GW_USER points at
--      tim1's firm-1 entity (the person), exactly what the GWAdmin link/delink
--      screen writes and what PersonRegistry follows. So when tim1 (already
--      authenticated, with a live Keycloak SSO session) lands on the firm-5
--      whitelabel host, OidcCallbackAction.switchToFirmAccount resolves the
--      person's firm-5 account → john, and the session is established AS john.
--
--   2. john.localhost resolves to firm 5 — SYSTEM_BASE_URL='john.localhost' is
--      an advisor-level whitelabel base URL, so AuthorizationManagerTrait
--      .IdentifyFirmByUrlMsg matches the host to firm 5 (CP_WHITELABEL_KEYWORD
--      'jhn' is the brand keyword). `*.localhost` resolves to 127.0.0.1 with no
--      /etc/hosts entry, so this is a usable dev host out of the box.
--
-- The login user mirrors the V17 firm-5 advisor row shape (ENTITY_TYPE 4,
-- active, not inactivated) so getActiveUsers lists it; no password hash (john
-- enters via the SSO firm-switch, never a credential form), no role/access set
-- (capability grants are a separate concern, cf. V14). The shared primary email
-- tim1@geowealth.int matches tim1's, keeping the "same person" story coherent
-- (the link itself is explicit via LINKED_GW_USER, not email-derived here).
--
-- Requires : V2 (firm 1 + tim1 — the link target) and V8 (firm 5 config).
-- Idempotent: INSERTs are NOT EXISTS-guarded and the trailing UPDATE re-asserts
-- the link/whitelabel, so a hand-created john (dev box) is corrected in place.
-- Also drives the e2e/tests/p1-login-newtab-john.spec.ts scenario 1:1.
--------------------------------------------------------------------------------

INSERT INTO ENTITY_TBL (ENTITY_ID,ENTITY_TYPE_CD,LDAP_UID,LDAP_PSWD_HASH,PSWD_EXPIRATION_DATE,PASSWORD_REMINDER,ENTITY_ACTIVE_FLAG,ENTITY_INACTIVE_DATE,LOGIN_INACTIVATED_FLAG,LOGIN_INACTIVATED_DATE,LOGIN_INACTIVATED_BY,LOGIN_INACTIVED_REASON_CD,PROSPECT_ONLY_FLAG,ALIAS1_UID,CREATED_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_BY,FIRM_CD,PERSONAL_ACCESS_SET_CD,DEFAULT_ROLE_CD,DOC_VAULT_ROOT_FOLDER,DOC_VAULT_CREDENTIALS_ID,AGREED_LEGAL_DATE,QPR_DEFAULT_TEMPLATE,QPR_DELIVERY_METHOD,ADVISOR_BIO_ID,SHOW_PORTFOLIO_CLPORTAL_FLAG,SYSTEM_BASE_URL,CLIENT_PORTAL_BASE_URL,MAX_PC_INTERVAL_IMPORT_EOM_DAT,LOGIN_ACTIVATION_SENT_DATE,INSURANCE_AGENT_FLAG,LOGIN_OVERRIDE_ID,SHOW_PORTFOLIOS_ADVPORTAL_FLAG,OVERRIDE_ID,CP_WHITELABEL_KEYWORD,ENABLE_BALANCE_SHEET,DEFAULT_BUNDLE_TEMPLATE_ID,GW_ADMIN_FLAG,TRADE_HOLD_FLAG,MFA_TOKEN,MFA_TOKEN_EXPIRATION_DATE,MFA_REQUIRED_FLAG,BILLING_DISCOUNT_TYPE,BILLING_DISCOUNT,BILLING_DISCOUNT_EXP_DATE,MM_BILLING_DISCOUNT_TYPE,MM_BILLING_DISCOUNT,MM_BILLING_DISCOUNT_EXP_DATE,PL_BILLING_DISCOUNT_TYPE,PL_BILLING_DISCOUNT,PL_BILLING_DISCOUNT_EXP_DATE,NO_EMAIL_FLAG,NO_MAIL_FLAG,NO_PHONE_FLAG,NO_TEXTMESSAGE_FLAG,NO_IM_FLAG,NO_FAX_FLAG,SOURCE_TYPE_CD,RATING_TYPE_CD,STAGE_TYPE_CD,NICKNAME,NOTES,INDUSTRY_TEMP_CODE_CD,OWNER,POTENTIAL,CUSTOM_SEARCH_DATA,DOC_PRIVATE_FLAG,DOC_NOTIFICATION_FLAG,PRIMARY_CONTACT_FLAG,CRM_ID,SHOW_SLEEVE_ALLOCATION_TAB_CL_PORTAL_FLAG,SHOW_CLIENTS_TAB_CLIENT_PORTAL,CL_PORTAL_ACCESS_LEVEL,CL_PORTAL_LOGIN_TARGET,LINKED_GW_USER,LOGIN_STATUS_CD,LOGIN_INACTIVATED_REASON_OTHER,MERGED_WITH_PROSPECT,NF_ACCOUNT_ID_OF_ACCOUNT_DETAILS,USE_CUSTODIAN_DATA_AS_PRIMARY_FLAG,USE_PRIMARY_CLIENT_DATA_AS_PRIMARY_FLAG)
SELECT '019E8978F9AE7676915751838956A526',4,'john',NULL,NULL,NULL,1,NULL,0,NULL,NULL,NULL,0,NULL,TO_DATE('2015-11-29 11:13:36','YYYY-MM-DD HH24:MI:SS'),'BB3DD0D9096646A09930D5822BED332E',TO_DATE('2024-07-23 00:00:00','YYYY-MM-DD HH24:MI:SS'),'0075D75FECDB41429186912AAFB4E605',5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'john.localhost',NULL,NULL,NULL,0,NULL,1,NULL,'jhn',0,NULL,0,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,'CFF4F4FD63BF4B4DA431DAE255748A52',0,NULL,0,0,0,NULL,0,0,NULL,NULL,'6459DFB4414B47DE9BFE9AC06205BD43',3,NULL,NULL,NULL,0,0
FROM dual WHERE NOT EXISTS (SELECT 1 FROM entity_tbl WHERE entity_id='019E8978F9AE7676915751838956A526');

INSERT INTO USER_DETAIL_TBL (ENTITY_ID,EMPLOYMENT_STATUS_CD,TITLE,GIVEN_NAME,SURNAME,COMMON_NAME,GENERATION_QUALIFIER,INITIALS,TAX_ID,HOME_ADDRESS_ID,MAILING_ADDRESS_ID,BILLING_ADDRESS_ID,BUSINESS_ADDRESS_ID,CREDITCARD_NUM,EXP_MONTH,EXP_YEAR,GENDER,BIRTHDATE,HINT_SIGNIFICANT_DATE,HINT_MOTHERS_MAIDEN_NAME,HOME_PHONE,HOME_FAX,WORK_PHONE,WORK_FAX,PREFERRED_PHONE,PAGER_PHONE,PAGER_EMAILADDRESS,EMAIL_ADDRESS,EMAIL_ADDRESS2,CELL_PHONE,EMPLOYER_NAME,OCCUPATION,RESIDENCE_COUNTRY,CITIZENSHIP_STATUS,WORK_RBD_FLAG,WORK_RBD_DETAIL,WORK_DIRECTOR_POC_FLAG,WORK_DIRECTOR_POC_DETAIL,MAIL_PREF_INTERIM_SH_INFO_FLAG,NF_EMPLOYEE_FAMILY_FLAG,NF_EMPLOYEE_FAMILY_NAME,NF_EMPLOYEE_FAMILY_RELAT,CREATED_DATE,LAST_UPDATE_DATE,CREATED_BY,LAST_UPDATE_BY,WEBSITE,SSNTID,GENDER_CD,CRD,PARTNERS,LICENSES,DESIGNATIONS,CUSTODIAN,MASTER_NUMBER,DBA,PRICING,SALUTATION,VENDOR_CONTACT_TYPE_CD,WORK_COMPANY,VENDOR_CONTACT_ROLE,NAME_SUFFIX,NCC_COMPANY_NAME,PROPOSAL_FEE_RATE,MARITAL_STATUS_CD,US_CITIZEN_FLAG,HIDE_DISABLED_WORKFLOWS,EMPLOYEE_TYPE_CD)
SELECT '019E8978F9AE7676915751838956A526',NULL,NULL,'John','Atanasov','Atanasov, John',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,TO_DATE('2015-11-29 11:13:33','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2026-06-02 00:00:00','YYYY-MM-DD HH24:MI:SS'),'CFF4F4FD63BF4B4DA431DAE255748A52','CFF4F4FD63BF4B4DA431DAE255748A52',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL
FROM dual WHERE NOT EXISTS (SELECT 1 FROM user_detail_tbl WHERE entity_id='019E8978F9AE7676915751838956A526');

INSERT INTO ENTITY_EMAIL_TBL (EMAIL_ID,ENTITY_ID,EMAIL_TYPE_CD,EMAIL,CREATED_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_BY,PRIMARY_EMAIL_FLAG,EMAIL_NAME,CRM_ID)
SELECT '019E897CAB8D7DBE9B771CA02B280F31','019E8978F9AE7676915751838956A526',30,'tim1@geowealth.int',TO_DATE('2026-06-02 00:00:00','YYYY-MM-DD HH24:MI:SS'),'CFF4F4FD63BF4B4DA431DAE255748A52',TO_DATE('2026-06-02 00:00:00','YYYY-MM-DD HH24:MI:SS'),'CFF4F4FD63BF4B4DA431DAE255748A52',1,NULL,NULL
FROM dual WHERE NOT EXISTS (SELECT 1 FROM entity_email_tbl WHERE entity_id='019E8978F9AE7676915751838956A526');

-- Re-assert the scenario state for an already-present john (e.g. a hand-created
-- dev row): link to the firm-1 person and expose the firm-5 whitelabel host.
UPDATE entity_tbl
   SET linked_gw_user = '6459DFB4414B47DE9BFE9AC06205BD43',
       system_base_url = 'john.localhost',
       cp_whitelabel_keyword = 'jhn'
 WHERE entity_id = '019E8978F9AE7676915751838956A526'
   AND ( linked_gw_user IS NULL
      OR system_base_url IS NULL
      OR cp_whitelabel_keyword IS NULL );

COMMIT;
