--------------------------------------------------------------------------------
-- V8__seed_firm5_c1wealth_whitelabel.sql
--
-- Seeds the whitelabel firm 5 ("CreativeOne Wealth") so the c1wealth whitelabel
-- host resolves and its `Firm#5` entity loads. Anonymous host->firm resolution
-- (`identifyFirmByUrl`) matches the request host against FIRM_TBL.SYSTEM_BASE_URL;
-- firm 5 carries SYSTEM_BASE_URL='c1wealth.geowealth.com' / CODE='c1wealth'.
-- Like firm 1 (see V7), the full Hibernate load of Firm#5 eager-refreshes the
-- firm-config graph, so the firm's adminsRole/allEmployeesRole (558/559),
-- defaultAccessSet (3185), businessAddress, and the constrained one-to-ones
-- (firmServiceRequest/firmTaxData/firmSSO) must all exist or the load throws
-- `UnresolvableObjectException: [Firm#5]` and the whitelabel host shows a blank
-- SPA.
--
-- Provenance : extracted from a GP prod-shape source, PII-SCRUBBED for this
--              public repo. The whitelabel routing identity (firm name, CODE,
--              SYSTEM_BASE_URL, portal/CRM URLs) is kept because it IS the demo's
--              functional config; the DocuSign Connect security key and the firm
--              contact phone are nulled, and the business address is synthetic.
-- Generated  : 2026-06-01. Applies on top of V1 (baseline). FIRM_TBL has no
--              outgoing DB-level FK, so the firm row is inserted first and its
--              children (which reference FIRM_CD=5) follow.
--------------------------------------------------------------------------------

-- firm 5 (CreativeOne Wealth / c1wealth whitelabel). DS_CONNECT_SECURITY_KEY and
-- PHONE nulled vs source; routing config retained.
INSERT INTO FIRM_TBL (FIRM_CD,FIRM_NAME,FIRM_ADV,BUSINESS_ADDRESS_ID,PHONE,FAX,FIRM_IARD,ALL_EMPLOYEES_ROLE,ADMINS_ROLE,DEFAULT_ACCESS_SET,CODE,SYSTEM_BASE_URL,POLICY_RULE_ID,SINGLE_TRADE_EBASKET_NAME,EBASKET_EXCL_ADV_BILLING_FLAG,EBASKET_EXCL_PL_BILLING_FLAG,EBASKET_EXCL_MM_BILLING_FLAG,CRM_SYNCHRONIZE_FLAG,CRM_URL,EXCL_UNAFF_CASH_PL_BILL_FLAG,DOC_VAULT_DATA_SRC,CLIENT_PORTAL_BASE_URL,DEFAULT_WORKFLOW_CD,DEFAULT_PROP_FIRM_CD,INCLUDE_BILLING_IN_QPR_FLAG,CASH_IN_COMPONENT_SUPPORT_FLAG,FIRM_URL,DOC_VAULT_DEFAULT_FOLDERS,DEMO,SHOW_PORTFOLIOS_ADVPORTAL_FLAG,CASH_BUFFER_PERCENT,CHECK_SEND_TO_BLOCK_TRADE_FLAG,SHOW_PROFILE_SECTION_FLAG,INACTIVE,REDTAIL_SYNCHRONIZE_FLAG,REACT_ADVISOR_LOGIN_ENABLED,SR_CENTER_ENABLED_FLAG,SUPPORT_EMAIL_ADDRESS,MFA_REQUIRED_FLAG,ALLOW_RISK_VECTOR_FLAG,EXCL_UNAFF_CASH_ADV_BILL_FLAG,MC_ENABLED_FLAG,NEW_RC_ENABLED_FLAG,RC_CENTER_URL,ROOT_FOLDER_ID,DIGITAL_ACC_OPEN_ENABLED_FLAG,DOCUSIGN_SUPPORT_EMAIL,UMA_TAB_FIRST_FLAG,MODEL_PROGRAMS_ENABLED_FLAG,BALANCE_SHEET_ENABLED_FLAG,BS_MANAGE_EXTERNAL_ACCOUNTS_FLAG,BS_MANAGE_MANUAL_ACCOUNTS_FLAG,DS_APP_CONFIG_ID,DS_CONSENT_CALLBACK_URL,DS_USER_ID,DS_APPROVAL_FILE,DS_REPLACE_ENVELOPE_EMAILS_FLAG,DS_CONNECT_SECURITY_KEY,PERMISSION_VERSION_CD,PROTECTED_VAULT_FOLDERS,HUBSPOT_ENABLED_FLAG,HUBSPOT_TRACKING_CODE,OTHER_SERVICE_REQUESTS_FLAG,OTHER_SERVICE_REQUESTS_URL,OTHER_SERVICE_REQUESTS_OA_FLAG,PROPOSAL_VERSION_CD,SHOW_UMA_PROD_CLNT_PORTAL_FLAG,SHOW_SLEEVE_ALLOCATION_TAB_CL_PORTAL_FLAG,DEFAULT_PROPOSAL_FEE_RATE,MIN_PROPOSAL_FEE_RATE,MAX_PROPOSAL_FEE_RATE,REQUIRES_EDIT_PERMISSION_PROPOSAL_FEE_RATE_FLAG,PROPOSAL_FEE_RATE_HELP_TEXT,SHOW_PORTFOLIO_CLPORTAL_FLAG,SECOND_CUSTOM_LINK_LABEL,SECOND_CUSTOM_LINK_URL,PRIVATE_VAULT_FOLDERS,SHOW_COST_BASIS_CLPORTAL_FLAG,SHOW_CLIENTS_TAB_CLIENT_PORTAL,EBASKET_EXCL_INTERNAL_ADV_BILLING_FLAG,EBASKET_EXCL_INTERNAL_PL_BILLING_FLAG,EBASKET_EXCL_INTERNAL_MM_BILLING_FLAG,EXCL_UNAFF_CASH_INTERNAL_ADV_BILL_FLAG,EXCL_UNAFF_CASH_INTERNAL_PL_BILL_FLAG,EXCL_UNAFF_CASH_MM_BILL_FLAG,EXCL_UNAFF_CASH_INTERNAL_MM_BILL_FLAG,MIN_QUALIFICATION_TE_PROXIES,TAX_MANAGEMENT_ENABLED_FLAG,MIN_QUALIFICATION_TLH_PROXIES,TAX_LOSS_HARVESTING_ENABLED_FLAG,INACTIVE_DATE,OPEN_ACCOUNT_SETTINGS_ENABLED_FLAG)
VALUES (5,'CreativeOne Wealth','281213','A7B5E9D4DD9E42A7BD6AC195C06EE378',NULL,' ','ChangePath',559,558,3185,'c1wealth','c1wealth.geowealth.com','DA286CF15BEB4AA3BBE6F9C0659BA462','Discretionary',0,0,0,1,'https://changepathcrm.geowealth.com/',0,'GeoWealth','c1wealthclient.geowealth.int',2,NULL,1,1,'http://creativeonewealth.com/',NULL,0,1,1.5,1,1,0,0,1,1,'enterpriseservices@geowealth.com',0,0,0,1,1,'https://adviser.creativeonewealth.com/resources','E9766480AAAD4DD431D03012F6B3F9DF',1,'geowealthtest+Firm@gmail.com',0,0,1,0,1,'C703E4EEEF5E47BF3861C351910CC187','https://platform.geowealth.com/ux/dsConsentCallback.do',NULL,'Approval',0,NULL,20,'/Proposals;',0,NULL,0,NULL,0,20,0,0,1.75,0.55,2,0,'The fee is the TOTAL fee charged to the client.',1,NULL,NULL,NULL,0,0,0,0,0,0,0,0,0,500,1,2500,1,NULL,1);

-- adminsRole (558) + allEmployeesRole (559) for firm 5
INSERT INTO ROLE_TBL (ROLE_CD,FIRM_CD,NAME,DESCRIPTION,DEFAULT_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE)
VALUES (558,5,'Admins','Firm Administrators',0,NULL,NULL,NULL,TO_DATE('2025-06-25 17:19:56','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ROLE_TBL (ROLE_CD,FIRM_CD,NAME,DESCRIPTION,DEFAULT_FLAG,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE)
VALUES (559,5,'All Employees','All employees of the firm has this role',1,NULL,NULL,NULL,TO_DATE('2025-06-30 20:06:36','YYYY-MM-DD HH24:MI:SS'));

-- defaultAccessSet (3185) for firm 5
INSERT INTO ACCESS_SET_TBL (ACCESS_SET_CD,NAME,DEFAULT_FLAG,DESCRIPTION,FIRM_CD,CREATED_BY,CREATED_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE)
VALUES (3185,'Default Firm AccessSet',1,'Default Firm AccessSet',5,NULL,NULL,NULL,TO_DATE('2026-03-02 11:51:01','YYYY-MM-DD HH24:MI:SS'));

-- businessAddress for firm 5 — synthetic values
INSERT INTO ENTITY_ADDRESS_TBL (ADDRESS_ID,ENTITY_ID,ADDRESS_TYPE_CD,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,CITY,STATE,COUNTRY,POSTAL_CODE,PRIMARY_ADDRESS_FLAG,COUNTY,CREATED_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_BY,CRM_ID)
VALUES ('A7B5E9D4DD9E42A7BD6AC195C06EE378',NULL,10,'11460 Tomahawk Creek Pkwy',NULL,NULL,'Leawood','KS','US','66211',0,'Johnson',NULL,NULL,TO_DATE('2026-03-18 18:49:12','YYYY-MM-DD HH24:MI:SS'),NULL,445940);

-- constrained one-to-ones referenced by Firm.hbm.xml (firm 5)
INSERT INTO FIRM_SERVICE_REQUEST_TBL (FIRM_CD,SR_CENTER_ENABLED_FLAG,OTHER_SERVICE_REQUESTS_FLAG,OTHER_SERVICE_REQUESTS_URL,OTHER_SERVICE_REQUESTS_OA_FLAG,SR_DISCRETIONARY_TRADING_EXECUTION_TYPE_CD,SR_DISCRETIONARY_TRADING_CUT_OFF_HOUR_TYPE,OTHER_SERVICE_REQUESTS_LABEL,REDIRECT_DISCRETIONARY_SRS_TO_FIRM_CD,SKIP_PASSWORD_VERIFICATION_FLAG)
VALUES (5,1,0,NULL,0,2,'SIXTEEN','Other Service Requests',5,0);
INSERT INTO FIRM_TAX_DATA_TBL (FIRM_CD,TE_PERMISSION_LEVEL_CD,TLH_PERMISSION_LEVEL_CD,TAX_TRANSITION_PERMISSION_LEVEL_CD,NEW_TAX_TIERS_AVAILABLE_FLAG)
VALUES (5,0,'off','off',1);
INSERT INTO FIRM_SSO_TBL (FIRM_CD,ENFORCEMENT_TYPE,CONFIG,LAST_UPDATED_DATE,LAST_UPDATED_BY)
VALUES (5,'off',NULL,NULL,NULL);

COMMIT;
