parent=keycloak
import=common/keycloak

styles=css/styles.css
scripts=js/auth-spa.js

stylesCommon=node_modules/@patternfly/patternfly/patternfly.min.css node_modules/@patternfly/patternfly/patternfly-additions.min.css

locales=en
